POST http://localhost:8080/devops_starter_war_exploded/api/person
Content-Type: application/json

{
  "fName": "Karl",
  "lName": "Petersen",
  "email": "test@test.dk",
  "hobbies": [
    {
      "id": 2
    }
  ],
  "phones": [
    {
      "nr": "2371617",
      "desc": "DKk"
    }
  ],
  "address": {
    "street": "kaster vej",
    "info": "236",
    "cityInfo": {
      "id": 1
    }
  }
}

###
GET http://localhost:8080/devops_starter_war_exploded/api/person/all

###

PUT http://localhost:8080/devops_starter_war_exploded/api/person/edit/10
Content-Type: application/json

{
  "fName": "Johannes",
  "lName": "Test",
  "email": "test@test.dk"
  }

###

PUT http://localhost:8080/devops_starter_war_exploded/api/person/editaddress/1
Content-Type: application/json

{
  "address": {
    "street": "kaster vej",
    "info": "236",
    "cityInfo": {
      "id": 1
    }
  }
}
###
POST http://localhost:8080/ca1_war_exploded/api/person/addphone/1
Content-Type: application/json

{
"phones": [
{
"nr": "7364646",
"desc": "DKk"
}
]
}